name: Deploy to Vercel

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd v1 && npm install
          cd ../v2 && npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          USER_INFO_GIST_ID: ${{ secrets.USER_INFO_GIST_ID }}
          USER_INFO_GIST_FILENAME: ${{ secrets.USER_INFO_GIST_FILENAME }}
          APP_URL: ${{ vars.APP_URL }}
        run: vercel --prod --yes --token $VERCEL_TOKEN --build-env MONGODB_URI=$MONGODB_URI --build-env USER_INFO_GIST_ID=$USER_INFO_GIST_ID --build-env USER_INFO_GIST_FILENAME=$USER_INFO_GIST_FILENAME --build-env APP_URL=$APP_URL --build-env NODE_ENV=production
